// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ebook/BACKUP_TOTAL_ESTRUTURA" | "/ebook/BACKUP_TOTAL_ESTRUTURA/cofre-v2_backup_20260404_2006" | "/ebook/BACKUP_TOTAL_ESTRUTURA/v2_final_61_pages" | "/ebook/cofre" | "/ebook/cofre-v2" | "/ebook/master-edition/vol-1-core" | "/ebook/viewer" | "/ebook/viewer/[id]" | "/hub" | "/login" | "/sais" | "/sais/upsell-1" | "/sais/vsl" | "/sais/vsl-upsell-1"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/ebook/BACKUP_TOTAL_ESTRUTURA": {}
  "/ebook/BACKUP_TOTAL_ESTRUTURA/cofre-v2_backup_20260404_2006": {}
  "/ebook/BACKUP_TOTAL_ESTRUTURA/v2_final_61_pages": {}
  "/ebook/cofre": {}
  "/ebook/cofre-v2": {}
  "/ebook/master-edition/vol-1-core": {}
  "/ebook/viewer": {}
  "/ebook/viewer/[id]": { "id": string; }
  "/hub": {}
  "/login": {}
  "/sais": {}
  "/sais/upsell-1": {}
  "/sais/vsl": {}
  "/sais/vsl-upsell-1": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
