// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/ebook/BACKUP_TOTAL_ESTRUTURA/cofre-v2_backup_20260404_2006/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/BACKUP_TOTAL_ESTRUTURA/cofre-v2_backup_20260404_2006">> = Specific
  const handler = {} as typeof import("../../../app/ebook/BACKUP_TOTAL_ESTRUTURA/cofre-v2_backup_20260404_2006/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/BACKUP_TOTAL_ESTRUTURA/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/BACKUP_TOTAL_ESTRUTURA">> = Specific
  const handler = {} as typeof import("../../../app/ebook/BACKUP_TOTAL_ESTRUTURA/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/BACKUP_TOTAL_ESTRUTURA/v2_final_61_pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/BACKUP_TOTAL_ESTRUTURA/v2_final_61_pages">> = Specific
  const handler = {} as typeof import("../../../app/ebook/BACKUP_TOTAL_ESTRUTURA/v2_final_61_pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/cofre-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/cofre-v2">> = Specific
  const handler = {} as typeof import("../../../app/ebook/cofre-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/cofre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/cofre">> = Specific
  const handler = {} as typeof import("../../../app/ebook/cofre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/master-edition/vol-1-core/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/master-edition/vol-1-core">> = Specific
  const handler = {} as typeof import("../../../app/ebook/master-edition/vol-1-core/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/viewer/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/viewer/[id]">> = Specific
  const handler = {} as typeof import("../../../app/ebook/viewer/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ebook/viewer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ebook/viewer">> = Specific
  const handler = {} as typeof import("../../../app/ebook/viewer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hub">> = Specific
  const handler = {} as typeof import("../../../app/hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sais/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sais">> = Specific
  const handler = {} as typeof import("../../../app/sais/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sais/upsell-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sais/upsell-1">> = Specific
  const handler = {} as typeof import("../../../app/sais/upsell-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sais/vsl-upsell-1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sais/vsl-upsell-1">> = Specific
  const handler = {} as typeof import("../../../app/sais/vsl-upsell-1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sais/vsl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sais/vsl">> = Specific
  const handler = {} as typeof import("../../../app/sais/vsl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
